# This job will execute the changeset_testlist.py script, which in turn will
# compute a list of tests that need to be executed.
# The script itself produces the correct output to set a variable for a future
# stage.

parameters:
- name: target_branch
  type: string
  default: "origin/master"
- name: skip_all_hw_tests
  type: boolean
  default: false

jobs:
  - job: analyze
    displayName: Analyze Changeset
    variables:
      - group: github-ettusresearch-uhddev
    pool:
      name: Drivers-NIBuildFarm-RFMIBUILD
      demands: sh
    steps:
    - checkout: self
      clean: true
    - bash: |
        if [[ $AGENT_OS == "Windows_NT" ]]; then
            VENV_BIN_DIR="Scripts"
        else
            VENV_BIN_DIR="bin"
        fi
        python3 -m venv $AGENT_TEMPDIRECTORY/ac_venv
        $AGENT_TEMPDIRECTORY/ac_venv/$VENV_BIN_DIR/pip install --upgrade pip
        $AGENT_TEMPDIRECTORY/ac_venv/$VENV_BIN_DIR/pip install ruamel.yaml clang-format==14.0.6 ni-python-styleguide requests
        git branch
        set -o xtrace
        if [ "$BUILD_REASON" == "PullRequest" ]; then
          EXTRA_ARGS="--github-label-api-endpoint https://oauth2:$OAUTH_TOKEN@api.github.com/repos/$BUILD_REPOSITORY_ID/issues/$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER/labels"
        fi
        if [ "$SKIP_HW_TESTS" == "true" ]; then
          EXTRA_ARGS="$EXTRA_ARGS --remove-test hw devtest"
        fi
        $AGENT_TEMPDIRECTORY/ac_venv/$VENV_BIN_DIR/python3 tools/changeset_testlist.py \
                --target-branch $TARGET_BRANCH \
                --set-azdo-var UhdTestList \
                --list-tests --verbose $EXTRA_ARGS
      name: gen_testlist
      displayName: Generate Test-List
      env:
        TARGET_BRANCH: ${{ parameters.target_branch }}
        OAUTH_TOKEN: $(github_uhddev_token)
        SKIP_HW_TESTS: ${{ parameters.skip_all_hw_tests }}
    - bash: |
        if [[ $AGENT_OS == "Windows_NT" ]]; then
            VENV_BIN_DIR="Scripts"
        else
            VENV_BIN_DIR="bin"
        fi
        source $AGENT_TEMPDIRECTORY/ac_venv/$VENV_BIN_DIR/activate
        if [[ $GEN_TESTLIST_UHDTESTLIST =~ "clang-format" ]]; then
            $AGENT_TEMPDIRECTORY/ac_venv/$VENV_BIN_DIR/python3 \
                tools/run-clang-format.py . -r --patch-file clang-format.patch \
                    --clang-format-executable `which clang-format`
        fi
      name: run_clang_format
      displayName: Conditionally run clang-format

    - publish: clang-format.patch
      artifact: clang-format patch file
      displayName: Publish clang-format patch file
      condition: failed()

